package com.mainone.model.sfa;

import java.util.Date;


/**
 * AbstractSfaLinkManInfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSfaLinkManInfo  implements java.io.Serializable {


    // Fields    

     private Integer linkManId;
     private Integer customerId;
     private Integer linkManCategory;
     private String linkManName;
     private String linkManAdd;
     private String linkManTel;
     private String linkManMobile;
     private String linkManFax;
     private String linkManZip;
     private Date addDate;
     private Integer linkManType;
     private String item1;
     private String item2;
     private String linkManQq;
     private String linkManMsn;
     private Date linkManBirthday;
     private Integer linkManSex;
     private String linkManEmail;
     private Integer mobileSplitInfoId;


    // Constructors

    /** default constructor */
    public AbstractSfaLinkManInfo() {
    }

	/** minimal constructor */
    public AbstractSfaLinkManInfo(Integer customerId, Integer linkManCategory, String linkManName, Date addDate, Integer linkManType, Integer linkManSex) {
        this.customerId = customerId;
        this.linkManCategory = linkManCategory;
        this.linkManName = linkManName;
        this.addDate = addDate;
        this.linkManType = linkManType;
        this.linkManSex = linkManSex;
    }
    
    /** full constructor */
    public AbstractSfaLinkManInfo(Integer customerId, Integer linkManCategory, String linkManName, String linkManAdd, String linkManTel, String linkManMobile, String linkManFax, String linkManZip, Date addDate, Integer linkManType, String item1, String item2, String linkManQq, String linkManMsn, Date linkManBirthday, Integer linkManSex, String linkManEmail, Integer mobileSplitInfoId) {
        this.customerId = customerId;
        this.linkManCategory = linkManCategory;
        this.linkManName = linkManName;
        this.linkManAdd = linkManAdd;
        this.linkManTel = linkManTel;
        this.linkManMobile = linkManMobile;
        this.linkManFax = linkManFax;
        this.linkManZip = linkManZip;
        this.addDate = addDate;
        this.linkManType = linkManType;
        this.item1 = item1;
        this.item2 = item2;
        this.linkManQq = linkManQq;
        this.linkManMsn = linkManMsn;
        this.linkManBirthday = linkManBirthday;
        this.linkManSex = linkManSex;
        this.linkManEmail = linkManEmail;
        this.mobileSplitInfoId = mobileSplitInfoId;
    }

   
    // Property accessors

    public Integer getLinkManId() {
        return this.linkManId;
    }
    
    public void setLinkManId(Integer linkManId) {
        this.linkManId = linkManId;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public Integer getLinkManCategory() {
        return this.linkManCategory;
    }
    
    public void setLinkManCategory(Integer linkManCategory) {
        this.linkManCategory = linkManCategory;
    }

    public String getLinkManName() {
        return this.linkManName;
    }
    
    public void setLinkManName(String linkManName) {
        this.linkManName = linkManName;
    }

    public String getLinkManAdd() {
        return this.linkManAdd;
    }
    
    public void setLinkManAdd(String linkManAdd) {
        this.linkManAdd = linkManAdd;
    }

    public String getLinkManTel() {
        return this.linkManTel;
    }
    
    public void setLinkManTel(String linkManTel) {
        this.linkManTel = linkManTel;
    }

    public String getLinkManMobile() {
        return this.linkManMobile;
    }
    
    public void setLinkManMobile(String linkManMobile) {
        this.linkManMobile = linkManMobile;
    }

    public String getLinkManFax() {
        return this.linkManFax;
    }
    
    public void setLinkManFax(String linkManFax) {
        this.linkManFax = linkManFax;
    }

    public String getLinkManZip() {
        return this.linkManZip;
    }
    
    public void setLinkManZip(String linkManZip) {
        this.linkManZip = linkManZip;
    }

    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    public Integer getLinkManType() {
        return this.linkManType;
    }
    
    public void setLinkManType(Integer linkManType) {
        this.linkManType = linkManType;
    }

    public String getItem1() {
        return this.item1;
    }
    
    public void setItem1(String item1) {
        this.item1 = item1;
    }

    public String getItem2() {
        return this.item2;
    }
    
    public void setItem2(String item2) {
        this.item2 = item2;
    }

    public String getLinkManQq() {
        return this.linkManQq;
    }
    
    public void setLinkManQq(String linkManQq) {
        this.linkManQq = linkManQq;
    }

    public String getLinkManMsn() {
        return this.linkManMsn;
    }
    
    public void setLinkManMsn(String linkManMsn) {
        this.linkManMsn = linkManMsn;
    }

    public Date getLinkManBirthday() {
        return this.linkManBirthday;
    }
    
    public void setLinkManBirthday(Date linkManBirthday) {
        this.linkManBirthday = linkManBirthday;
    }

    public Integer getLinkManSex() {
        return this.linkManSex;
    }
    
    public void setLinkManSex(Integer linkManSex) {
        this.linkManSex = linkManSex;
    }

    public String getLinkManEmail() {
        return this.linkManEmail;
    }
    
    public void setLinkManEmail(String linkManEmail) {
        this.linkManEmail = linkManEmail;
    }

    public Integer getMobileSplitInfoId() {
        return this.mobileSplitInfoId;
    }
    
    public void setMobileSplitInfoId(Integer mobileSplitInfoId) {
        this.mobileSplitInfoId = mobileSplitInfoId;
    }
   








}