package com.mainone.model.sfa;

import java.util.Date;


/**
 * AbstractSfaUseFlowInfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSfaUseFlowInfo  implements java.io.Serializable {


    // Fields    

     private Integer useFlowId;
     private Integer customerId;
     private Integer employeeId;
     private Integer departId;
     private Integer companyId;
     private Integer areaId;
     private Date startTime;
     private Date endTime;
     private String status;
     private String remark;
     private Date operateTime;
     private Integer customerComeId;
     private String ifAddSelf;
     private String resourceState;


    // Constructors

    /** default constructor */
    public AbstractSfaUseFlowInfo() {
    }

    
    /** full constructor */
    public AbstractSfaUseFlowInfo(Integer customerId, Integer employeeId, Integer departId, Integer companyId, Integer areaId, Date startTime, Date endTime, String status, String remark, Date operateTime, Integer customerComeId, String ifAddSelf, String resourceState) {
        this.customerId = customerId;
        this.employeeId = employeeId;
        this.departId = departId;
        this.companyId = companyId;
        this.areaId = areaId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.remark = remark;
        this.operateTime = operateTime;
        this.customerComeId = customerComeId;
        this.ifAddSelf = ifAddSelf;
        this.resourceState = resourceState;
    }

   
    // Property accessors

    public Integer getUseFlowId() {
        return this.useFlowId;
    }
    
    public void setUseFlowId(Integer useFlowId) {
        this.useFlowId = useFlowId;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    public Integer getDepartId() {
        return this.departId;
    }
    
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Integer getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Date getOperateTime() {
        return this.operateTime;
    }
    
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    public Integer getCustomerComeId() {
        return this.customerComeId;
    }
    
    public void setCustomerComeId(Integer customerComeId) {
        this.customerComeId = customerComeId;
    }

    public String getIfAddSelf() {
        return this.ifAddSelf;
    }
    
    public void setIfAddSelf(String ifAddSelf) {
        this.ifAddSelf = ifAddSelf;
    }

    public String getResourceState() {
        return this.resourceState;
    }
    
    public void setResourceState(String resourceState) {
        this.resourceState = resourceState;
    }
   








}