package com.mainone.model.sfa;

import java.util.Date;


/**
 * AbstractSfaCustomerInfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSfaCustomerInfo  implements java.io.Serializable {


    // Fields    

     private Integer customerId;
     private String companyName;
     private String companyAdd;
     private String customerTel;
     private String customerFax;
     private String customerZip;
     private Integer customerComeId;
     private Integer employeeId;
     private Integer departId;
     private Integer companyId;
     private Integer areaId;
     private Date addDate;
     private Integer state;
     private String item1;
     private Integer urlState;
     private String item2;
     private Date portectBeginTime;
     private Date portectEndTime;
     private Integer portectState;
     private Integer addId;
     private Integer mobileSplitInfoId;
     private Integer companyType;
     private String customerProduct;
     private Integer insertNo;
     private Integer misCustomerId;
     private Integer useNum;
     private Date lastUseTime;
     private Integer mis2customerId;
     private Integer mis3customerId;
     private Integer chengjiaoUserId;
     private String industry;
     private String cusRemark;
     private Date chengjiaoTime;
     private String ifGenjin;
     private String ifBaifang;
     private Date lastPrintTime;
     private String resourceState;
     private String dataSource;
     private String cusLevel;
     private String mainName;
     private String tagIds;
     private String tagNames;
     private String manager;
     private Integer extendTimes;
     private String myProtest;


    // Constructors

    /** default constructor */
    public AbstractSfaCustomerInfo() {
    }

	/** minimal constructor */
    public AbstractSfaCustomerInfo(String companyName, String companyAdd, String customerTel, Integer customerComeId, Integer employeeId, Integer departId, Integer companyId, Integer areaId, Date addDate, Integer state) {
        this.companyName = companyName;
        this.companyAdd = companyAdd;
        this.customerTel = customerTel;
        this.customerComeId = customerComeId;
        this.employeeId = employeeId;
        this.departId = departId;
        this.companyId = companyId;
        this.areaId = areaId;
        this.addDate = addDate;
        this.state = state;
    }
    
    /** full constructor */
    public AbstractSfaCustomerInfo(String companyName, String companyAdd, String customerTel, String customerFax, String customerZip, Integer customerComeId, Integer employeeId, Integer departId, Integer companyId, Integer areaId, Date addDate, Integer state, String item1, Integer urlState, String item2, Date portectBeginTime, Date portectEndTime, Integer portectState, Integer addId, Integer mobileSplitInfoId, Integer companyType, String customerProduct, Integer insertNo, Integer misCustomerId, Integer useNum, Date lastUseTime, Integer mis2customerId, Integer mis3customerId, Integer chengjiaoUserId, String industry, String cusRemark, Date chengjiaoTime, String ifGenjin, String ifBaifang, Date lastPrintTime, String resourceState, String dataSource, String cusLevel, String mainName, String tagIds, String tagNames, String manager, Integer extendTimes, String myProtest) {
        this.companyName = companyName;
        this.companyAdd = companyAdd;
        this.customerTel = customerTel;
        this.customerFax = customerFax;
        this.customerZip = customerZip;
        this.customerComeId = customerComeId;
        this.employeeId = employeeId;
        this.departId = departId;
        this.companyId = companyId;
        this.areaId = areaId;
        this.addDate = addDate;
        this.state = state;
        this.item1 = item1;
        this.urlState = urlState;
        this.item2 = item2;
        this.portectBeginTime = portectBeginTime;
        this.portectEndTime = portectEndTime;
        this.portectState = portectState;
        this.addId = addId;
        this.mobileSplitInfoId = mobileSplitInfoId;
        this.companyType = companyType;
        this.customerProduct = customerProduct;
        this.insertNo = insertNo;
        this.misCustomerId = misCustomerId;
        this.useNum = useNum;
        this.lastUseTime = lastUseTime;
        this.mis2customerId = mis2customerId;
        this.mis3customerId = mis3customerId;
        this.chengjiaoUserId = chengjiaoUserId;
        this.industry = industry;
        this.cusRemark = cusRemark;
        this.chengjiaoTime = chengjiaoTime;
        this.ifGenjin = ifGenjin;
        this.ifBaifang = ifBaifang;
        this.lastPrintTime = lastPrintTime;
        this.resourceState = resourceState;
        this.dataSource = dataSource;
        this.cusLevel = cusLevel;
        this.mainName = mainName;
        this.tagIds = tagIds;
        this.tagNames = tagNames;
        this.manager = manager;
        this.extendTimes = extendTimes;
        this.myProtest = myProtest;
    }

   
    // Property accessors

    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyAdd() {
        return this.companyAdd;
    }
    
    public void setCompanyAdd(String companyAdd) {
        this.companyAdd = companyAdd;
    }

    public String getCustomerTel() {
        return this.customerTel;
    }
    
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    public String getCustomerFax() {
        return this.customerFax;
    }
    
    public void setCustomerFax(String customerFax) {
        this.customerFax = customerFax;
    }

    public String getCustomerZip() {
        return this.customerZip;
    }
    
    public void setCustomerZip(String customerZip) {
        this.customerZip = customerZip;
    }

    public Integer getCustomerComeId() {
        return this.customerComeId;
    }
    
    public void setCustomerComeId(Integer customerComeId) {
        this.customerComeId = customerComeId;
    }

    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    public Integer getDepartId() {
        return this.departId;
    }
    
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Integer getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

    public String getItem1() {
        return this.item1;
    }
    
    public void setItem1(String item1) {
        this.item1 = item1;
    }

    public Integer getUrlState() {
        return this.urlState;
    }
    
    public void setUrlState(Integer urlState) {
        this.urlState = urlState;
    }

    public String getItem2() {
        return this.item2;
    }
    
    public void setItem2(String item2) {
        this.item2 = item2;
    }

    public Date getPortectBeginTime() {
        return this.portectBeginTime;
    }
    
    public void setPortectBeginTime(Date portectBeginTime) {
        this.portectBeginTime = portectBeginTime;
    }

    public Date getPortectEndTime() {
        return this.portectEndTime;
    }
    
    public void setPortectEndTime(Date portectEndTime) {
        this.portectEndTime = portectEndTime;
    }

    public Integer getPortectState() {
        return this.portectState;
    }
    
    public void setPortectState(Integer portectState) {
        this.portectState = portectState;
    }

    public Integer getAddId() {
        return this.addId;
    }
    
    public void setAddId(Integer addId) {
        this.addId = addId;
    }

    public Integer getMobileSplitInfoId() {
        return this.mobileSplitInfoId;
    }
    
    public void setMobileSplitInfoId(Integer mobileSplitInfoId) {
        this.mobileSplitInfoId = mobileSplitInfoId;
    }

    public Integer getCompanyType() {
        return this.companyType;
    }
    
    public void setCompanyType(Integer companyType) {
        this.companyType = companyType;
    }

    public String getCustomerProduct() {
        return this.customerProduct;
    }
    
    public void setCustomerProduct(String customerProduct) {
        this.customerProduct = customerProduct;
    }

    public Integer getInsertNo() {
        return this.insertNo;
    }
    
    public void setInsertNo(Integer insertNo) {
        this.insertNo = insertNo;
    }

    public Integer getMisCustomerId() {
        return this.misCustomerId;
    }
    
    public void setMisCustomerId(Integer misCustomerId) {
        this.misCustomerId = misCustomerId;
    }

    public Integer getUseNum() {
        return this.useNum;
    }
    
    public void setUseNum(Integer useNum) {
        this.useNum = useNum;
    }

    public Date getLastUseTime() {
        return this.lastUseTime;
    }
    
    public void setLastUseTime(Date lastUseTime) {
        this.lastUseTime = lastUseTime;
    }

    public Integer getMis2customerId() {
        return this.mis2customerId;
    }
    
    public void setMis2customerId(Integer mis2customerId) {
        this.mis2customerId = mis2customerId;
    }

    public Integer getMis3customerId() {
        return this.mis3customerId;
    }
    
    public void setMis3customerId(Integer mis3customerId) {
        this.mis3customerId = mis3customerId;
    }

    public Integer getChengjiaoUserId() {
        return this.chengjiaoUserId;
    }
    
    public void setChengjiaoUserId(Integer chengjiaoUserId) {
        this.chengjiaoUserId = chengjiaoUserId;
    }

    public String getIndustry() {
        return this.industry;
    }
    
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getCusRemark() {
        return this.cusRemark;
    }
    
    public void setCusRemark(String cusRemark) {
        this.cusRemark = cusRemark;
    }

    public Date getChengjiaoTime() {
        return this.chengjiaoTime;
    }
    
    public void setChengjiaoTime(Date chengjiaoTime) {
        this.chengjiaoTime = chengjiaoTime;
    }

    public String getIfGenjin() {
        return this.ifGenjin;
    }
    
    public void setIfGenjin(String ifGenjin) {
        this.ifGenjin = ifGenjin;
    }

    public String getIfBaifang() {
        return this.ifBaifang;
    }
    
    public void setIfBaifang(String ifBaifang) {
        this.ifBaifang = ifBaifang;
    }

    public Date getLastPrintTime() {
        return this.lastPrintTime;
    }
    
    public void setLastPrintTime(Date lastPrintTime) {
        this.lastPrintTime = lastPrintTime;
    }

    public String getResourceState() {
        return this.resourceState;
    }
    
    public void setResourceState(String resourceState) {
        this.resourceState = resourceState;
    }

    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    public String getCusLevel() {
        return this.cusLevel;
    }
    
    public void setCusLevel(String cusLevel) {
        this.cusLevel = cusLevel;
    }

    public String getMainName() {
        return this.mainName;
    }
    
    public void setMainName(String mainName) {
        this.mainName = mainName;
    }

    public String getTagIds() {
        return this.tagIds;
    }
    
    public void setTagIds(String tagIds) {
        this.tagIds = tagIds;
    }

    public String getTagNames() {
        return this.tagNames;
    }
    
    public void setTagNames(String tagNames) {
        this.tagNames = tagNames;
    }

    public String getManager() {
        return this.manager;
    }
    
    public void setManager(String manager) {
        this.manager = manager;
    }

    public Integer getExtendTimes() {
        return this.extendTimes;
    }
    
    public void setExtendTimes(Integer extendTimes) {
        this.extendTimes = extendTimes;
    }

    public String getMyProtest() {
        return this.myProtest;
    }
    
    public void setMyProtest(String myProtest) {
        this.myProtest = myProtest;
    }
   








}