package com.mainone.model.sfa;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SfaCustomerInfo generated by MyEclipse - Hibernate Tools
 */
public class SfaCustomerInfo extends AbstractSfaCustomerInfo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SfaCustomerInfo() {
    }

	/** minimal constructor */
    public SfaCustomerInfo(String companyName, String companyAdd, String customerTel, Integer customerComeId, Integer employeeId, Integer departId, Integer companyId, Integer areaId, Date addDate, Integer state) {
        super(companyName, companyAdd, customerTel, customerComeId, employeeId, departId, companyId, areaId, addDate, state);        
    }
    
    /** full constructor */
    public SfaCustomerInfo(String companyName, String companyAdd, String customerTel, String customerFax, String customerZip, Integer customerComeId, Integer employeeId, Integer departId, Integer companyId, Integer areaId, Date addDate, Integer state, String item1, Integer urlState, String item2, Date portectBeginTime, Date portectEndTime, Integer portectState, Integer addId, Integer mobileSplitInfoId, Integer companyType, String customerProduct, Integer insertNo, Integer misCustomerId, Integer useNum, Date lastUseTime, Integer mis2customerId, Integer mis3customerId, Integer chengjiaoUserId, String industry, String cusRemark, Date chengjiaoTime, String ifGenjin, String ifBaifang, Date lastPrintTime, String resourceState, String dataSource, String cusLevel, String mainName, String tagIds, String tagNames, String manager, Integer extendTimes, String myProtest) {
        super(companyName, companyAdd, customerTel, customerFax, customerZip, customerComeId, employeeId, departId, companyId, areaId, addDate, state, item1, urlState, item2, portectBeginTime, portectEndTime, portectState, addId, mobileSplitInfoId, companyType, customerProduct, insertNo, misCustomerId, useNum, lastUseTime, mis2customerId, mis3customerId, chengjiaoUserId, industry, cusRemark, chengjiaoTime, ifGenjin, ifBaifang, lastPrintTime, resourceState, dataSource, cusLevel, mainName, tagIds, tagNames, manager, extendTimes, myProtest);        
    }
   
}
