package com.mainone.model.sfa;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SfaUseFlowInfo generated by MyEclipse - Hibernate Tools
 */
public class SfaUseFlowInfo extends AbstractSfaUseFlowInfo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SfaUseFlowInfo() {
    }

    
    /** full constructor */
    public SfaUseFlowInfo(Integer customerId, Integer employeeId, Integer departId, Integer companyId, Integer areaId, Date startTime, Date endTime, String status, String remark, Date operateTime, Integer customerComeId, String ifAddSelf, String resourceState) {
        super(customerId, employeeId, departId, companyId, areaId, startTime, endTime, status, remark, operateTime, customerComeId, ifAddSelf, resourceState);        
    }
   
}
